export enum RequestPath {
  Auth = "/users/current",
  Login = "/auth/login",
  Logout = "/auth/logout",
  Upload = "/upload/file",
  CreteHr = "/hr",
  GetStudents = "/students",
  GetInterview = "/interview",
  GetOneStudent = "/students/",
  User = "/users/",
  GetOneHr = "/Hr/",
  CreateStudent = "/students/register/",
  SendPasswordReset = "/auth/password/reset/request",
  PasswordReset = "/auth/password/reset",
  RegisterHr = "/hr/register/",
}
